#ifndef APPLICATION_CONFIG_H
#define APPLICATION_CONFIG_H


#define U14_CONTROLLER_DEADZONE 150u
#define U12_CONTROLLER_DEADZONE 50u

#define ADC_IIR_FILTER_COEFFICIENT 0.1f

// I2C
#define I2C_MASTER_SDA_IO   8
#define I2C_MASTER_SCL_IO   9
#define I2C_FREQUENCY_HZ    100000  // 100 kHz
#define I2C_TIMEOUT_MS      20u
#define I2C_SCAN_TIMEOUT_MS 500u

#define MT6701_I2C_ADDRESS 0x06
#define TCA9548A_I2C_ADDRESS 0x70

// SPI
#define SPI_SCLK_PIN_NUM 4u
#define SPI_MISO_PIN_NUM 5u
#define SPI_MOSI_PIN_NUM 6u
#define SPI_CS_PIN_NUM   7u

#define SPI_QUEUE_SIZE 7u
#define SPI_CLOCK_SPEED_HZ 1000000

#define NRF24L01_TRANSFER_SIZE_BYTES 33u  // NRF max transfer size is 32, +1 for W_TX_PAYLOAD 


#define APPLICATION_REFRESH_PERIOD_MS 10u


#endif